{
	"login1": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"changeOwnPassword": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"changePassword1": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"checkLogin": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"listAdmins": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"createAdminUser": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getById": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"disableAdminUser": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"enableAdminUser": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getAdmins": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"logout1": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"updateAdminUser": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"setProperty1": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"listApiKeys": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"createApiKey": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"listEnabledApiKeys": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"setEnabled": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"delete": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getClientConfig1": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"reloadDeploySettings": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getClientConfig2": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"setClientConfig": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"compareEnvironmentConfiguration": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"compareEnvironmentConfigurationFromRemote": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getEnvironmentConfiguration": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"setEnvironmentConfiguration": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getDeploySettings": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"putDeploySettings": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getPropertyDefinitions": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getServerEnviroment": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"oomtest": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"resetProperty": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getProperty": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"setProperty2": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getProperties": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"announceServer": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getServiceConfig": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"setServiceServerStatus": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getCategory1": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getCategory2": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"setCategory1": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"removeCategory": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"removeArrayCategory": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"changeArrayCategory": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getAll1": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getTemplate1": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"setTemplate": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"resetTemplate": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"listTemplates": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getCategory4": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getAll2": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"setCategory2": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"heapDump": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"hotspotDump": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"clearEmailTemplate": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"listEmailTemplate": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"updateEmailTemplate": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"pollForEventsRestricted": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"pollForEvents": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getEvents1": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"sendTestEventToAll": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"sendTestEventToAllLimited": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"sendTestEventToAllTagged": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"sendTestEventToAllUnique": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"sendTestEventToAllVersioned": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"sendTestEventToRestricted": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"sendTestEventToUser": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getEvents2": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"queueMessage": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"queueTestList": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"queueTest": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"sendTargetedMessage": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"post": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"addFeedBack": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"createFeedbackRequest": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"createFeedbackRequestNotAuthenticated": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"formUpload": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getResourceFile": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"jsTestUpload": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"jsUpload1": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"jsUpload2": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getInit1": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"get": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"callback": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getInit2": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"addAndroidUpdate": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"updateAndroidUpdate": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"removeAndroidUpdate": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getAllAndroidUpdates": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"callbackNonOrganic": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"callbackOrganic": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getAvatarsForType": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getAvatar": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"updateAvatar": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"removeAvatar": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getAllAvatars": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"addAvatar": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getBannerZones": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"createBannerZone": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"removeBannerZones": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getBannerCreative": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"updateBannerCreative": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getBannerCreatives": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"createBannerCreative": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"removeBannerCreatives": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getBannerZone": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"updateBannerZone": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"startContest1": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"importBaseballStatsEvent": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"listBaseballStatsEvents": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"exportBaseballStatsEvent": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"login2": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"logout2": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"balance": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"playerChanged": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"register": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getNotifications": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getCategory3": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"exportList": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"importList": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"test1": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getArchivedContest": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getArchivedContests": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"placeBet": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"activateAdcolonyVideo": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"activateAdcolonyVideoFallback": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getPropositions": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"join": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"subscribe": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"unsubscribe": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getTeams1": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getTeam1": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getContest": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"deleteContest": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"addProposition": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"removePropositions": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"addVideoProposition": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"removeVideoPropositions": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"changeTurnResult": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"closeVideoProposition": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"lockProposition": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"openProposition": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"openVideoProposition": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getProposition": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"updateProposition": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"removeProposition": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"updateVideoProposition": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"removeVideoProposition": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"reOpenProposition": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"rollbackProposition": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"setAutoStartNextProposition": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"finishContest": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"publishContest": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"setContestFinishing": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"startContest2": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"addPropositionFromTemplate": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"resolveProposition": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getUserContestHistory": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getUserRoomsForContest": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getGame": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"updateGame": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"deleteGame": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getGames": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"createGame": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"finishGame": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"closeGameAndContests": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"resetGame": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"createGameAndContests": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getGameContests": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"updateGameAndContests": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"updateStatsDelay": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"createResolveDoc": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getResolveDoc": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"updateResolveDoc": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"deleteResolveDoc": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getAllResolveDocs": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getStatsEventIds": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"setOverridden": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getStats": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"updateStats": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getTemplate2": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"updateTemplate": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"deleteTemplate": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"createTemplate": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getTemplatesForSport": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getTeams2": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"createTeam": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getTeam2": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"updateTeam": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"deleteTeam": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getAllTieredRewardModels": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"createTieredRewardModel": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getActiveTieredRewardModels": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getTieredRewardModel": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"updateTieredRewardModel": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"cashBetBalance": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"cashBetTransfer": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"cleanupClosedGameSNSTopics": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"fakeVerifyEmail": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getDuplicateParticipants": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"testConnectionClosed": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getStreamingLeaderboardExport": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"cancelFriend": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getFriends": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"invite1": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getFriendsLeaderboard": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"accept": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getRoomTypeLeaderboard1": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getRoomTypeLeaderboard2": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"leave": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"sendChatMessage": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"invite2": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"reportChatUser1": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"createLeague": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getLeagueHistoryLeaderboard": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"acceptInvite": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"declineInvite": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getLeague1": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"updateLeague": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getLeagueHistory": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"kick": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"demote": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getAvatars": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"promote": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getLeagueStats": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"exportLeagues": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getLeague2": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"sendMessage": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"enableAllEndpoints": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"enableEndpointArn": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"putSNSTemplate": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"test2": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getRoom": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"joinRoom": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"reportChatUser2": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"leaveRoom": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"sendRoomMessage": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getPayoutModel1": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"updatePayoutModel1": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getAllPayoutModels1": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"createPayoutModel1": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getActivePayoutModels1": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getRoomTags": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"createRoomTag": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"removeRoomTags": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getPayoutModel2": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"updatePayoutModel2": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getAllPayoutModels2": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"createPayoutModel2": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getActivePayoutModels2": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getRoomType": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"updateRoomType": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getAllRoomTypes": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"createRoomType": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getActiveRoomTypes": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getSport": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"updateSport": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"deleteSport": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getAllSports": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"createSport": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"changePassword2": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"logout3": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"deleteUser": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"addFacebookCredentials": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"removeFacebookCredentials": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"registerAsGuest": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"registerWithEmail": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"registerWithFacebook": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"toggleTeamNotifications": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"enableActionNotifications": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"enableGlobalNotifications": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"reportUser": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"updateClientDataStore": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"updateProfileFields": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"changeEmail1": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"requestVerifiedEmailChange": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getTransactionHistory1": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"handleChangePasswordByToken": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"handleEmailComplaint": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"handleUserVerification": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"loginWithAuthenticationToken": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"loginWithCashBet": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"loginWithEmail": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"loginWithEmailAndPassword": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"loginWithFacebook": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"requestUserVerification": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"deauthorizeFacebookCallback": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"forgotPassword": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"forgotPasswordByEmail": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getClientIp": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"handleVerifiedEmailChange": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"searchByCriteria": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"setRequiredActionData": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"toggleAutoLogin": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"updateDisplayName": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getUser1": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getState": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getReportedUser": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"updateReportedUser": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getReportedUsers": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
},{
	"getUsers": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"updateProfile": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"addAdminTransaction": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"changeEmail2": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getTransactionHistory2": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"importExternalWinviewProperties": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"setBlocked": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"addAdminTransactionFromApi": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"changePayPalEmail": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}",
	"getUser2": "function (t){var u=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};return e.execute((0,l.default)({spec:e.spec},(0,f.default)(e,\"requestInterceptor\",\"responseInterceptor\",\"userFetch\"),{pathName:r,method:n,parameters:t,operationId:a},u))}"
}